nelmio_cors:
  defaults:
    allow_origin: ["http://localhost:5173"] # Remplacez cette URL par l'URL de votre application Vue.js
    allow_methods: ["GET", "POST", "PUT", "DELETE"]
    allow_headers: ["Content-Type"]
    expose_headers: []
    max_age: 3600
    hosts: []
    origin_regex: false
    forced_allow_origin_value: ~
  paths:
    "^/api/":
      allow_origin: ["*"]
      allow_headers: ["*"]
      allow_methods: ["OPTIONS", "GET", "POST", "PUT", "DELETE"]
      max_age: 3600
